export const Users = [
  {
    id: 1,
    first_name: "Carlita",
    ip_address: "http://dummyimage.com/235x100.png/ff4444/ffffff",
  },
  {
    id: 2,
    first_name: "Harriot",
    ip_address: "http://dummyimage.com/193x100.png/ff4444/ffffff",
  },
  {
    id: 3,
    first_name: "Jacquenette",
    ip_address: "http://dummyimage.com/159x100.png/ff4444/ffffff",
  },
  {
    id: 4,
    first_name: "Sheppard",
    ip_address: "http://dummyimage.com/226x100.png/dddddd/000000",
  },
  {
    id: 5,
    first_name: "Gwennie",
    ip_address: "http://dummyimage.com/247x100.png/5fa2dd/ffffff",
  },
  {
    id: 6,
    first_name: "Alikee",
    ip_address: "http://dummyimage.com/174x100.png/cc0000/ffffff",
  },
  {
    id: 7,
    first_name: "Sharon",
    ip_address: "http://dummyimage.com/151x100.png/5fa2dd/ffffff",
  },
  {
    id: 8,
    first_name: "Jaymee",
    ip_address: "http://dummyimage.com/181x100.png/dddddd/000000",
  },
  {
    id: 9,
    first_name: "Florenza",
    ip_address: "http://dummyimage.com/200x100.png/dddddd/000000",
  },
  {
    id: 10,
    first_name: "Jody",
    ip_address: "http://dummyimage.com/101x100.png/cc0000/ffffff",
  },
  {
    id: 11,
    first_name: "Craggy",
    ip_address: "http://dummyimage.com/146x100.png/dddddd/000000",
  },
  {
    id: 12,
    first_name: "Magdaia",
    ip_address: "http://dummyimage.com/115x100.png/dddddd/000000",
  },
  {
    id: 13,
    first_name: "Shaughn",
    ip_address: "http://dummyimage.com/140x100.png/ff4444/ffffff",
  },
  {
    id: 14,
    first_name: "Hilary",
    ip_address: "http://dummyimage.com/130x100.png/5fa2dd/ffffff",
  },
  {
    id: 15,
    first_name: "Rickert",
    ip_address: "http://dummyimage.com/205x100.png/dddddd/000000",
  },
  {
    id: 16,
    first_name: "Orsa",
    ip_address: "http://dummyimage.com/244x100.png/ff4444/ffffff",
  },
  {
    id: 17,
    first_name: "Nessie",
    ip_address: "http://dummyimage.com/208x100.png/cc0000/ffffff",
  },
  {
    id: 18,
    first_name: "Adelbert",
    ip_address: "http://dummyimage.com/212x100.png/dddddd/000000",
  },
  {
    id: 19,
    first_name: "Roley",
    ip_address: "http://dummyimage.com/120x100.png/5fa2dd/ffffff",
  },
  {
    id: 20,
    first_name: "Marabel",
    ip_address: "http://dummyimage.com/136x100.png/dddddd/000000",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/ahsan.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets//4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
