export const Users = [
  {
    id: 1,
    first_name: "Carlita",
    picture: "assets2/1.jpg",
  },
  {
    id: 2,
    first_name: "Harriot",
    picture: "assets2/2.jpg",
  },
  {
    id: 3,
    first_name: "Jacquenette",
    picture: "assets2/3.jpg",
  },
  {
    id: 4,
    first_name: "Sheppard",
    picture: "assets2/4.jpg",
  },
  {
    id: 5,
    first_name: "Gwennie",
    picture: "assets2/5.jpg",
  },
  {
    id: 6,
    first_name: "Alikee",
    picture: "assets2/ahsan.jpg",
  },
  {
    id: 7,
    first_name: "Sharon",
    picture: "assets2/1.jpg",
  },
  {
    id: 8,
    first_name: "Jaymee",
    picture: "assets2/5.jpg",
  },
  {
    id: 9,
    first_name: "Florenza",
    picture: "assets2/1.jpg",
  },
  {
    id: 10,
    first_name: "Jody",
    picture: "assets2/4.jpg",
  },
  {
    id: 11,
    first_name: "Craggy",
    picture: "assets2/1.jpg",
  },
  {
    id: 12,
    first_name: "Magdaia",
    picture: "assets2/1.jpg",
  },
  {
    id: 13,
    first_name: "Shaughn",
    picture: "assets2/1.jpg",
  },
  {
    id: 14,
    first_name: "Hilary",
    picture: "assets2/1.jpg",
  },
  {
    id: 15,
    first_name: "Rickert",
    picture: "assets2/2.jpg",
  },
  {
    id: 16,
    first_name: "Orsa",
    picture: "assets2/3.jpg",
  },
  {
    id: 17,
    first_name: "Nessie",
    picture: "assets2/4.jpg",
  },
  {
    id: 18,
    first_name: "Adelbert",
    picture: "assets2/5.jpg",
  },
  {
    id: 19,
    first_name: "Roley",
    picture: "assets2/ahsan.jpg",
  },
  {
    id: 20,
    first_name: "Marabel",
    picture: "http://dummyimage.com/136x100.png/dddddd/000000",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/postimg/p1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/postimg/p2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/postimg/p3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/postimg/p4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/postimg/p5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/postimg/p6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/postimg/p7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/postimg/p8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "hi dear",
    photo: "assets/postimg/p9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/postimg/p10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
